import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  // Electronics (20 items)
  {
    name: "Premium Wireless Noise-Cancelling Headphones",
    description: "Experience immersive audio with our flagship noise-cancelling headphones. Features 40-hour battery life, adaptive ANC, spatial audio support, and premium memory foam ear cushions.",
    price: 349.99,
    comparePrice: 449.99,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800"],
    category: "Electronics",
    subcategory: "Audio",
    brand: "SoundWave Pro",
    sku: "SWP-WH-001",
    stock: 150,
    rating: 4.8,
    reviewCount: 2456,
    tags: ["headphones", "wireless", "noise-cancelling", "premium", "bluetooth"],
    isFeatured: true,
  },
  {
    name: "Ultra-Slim 4K OLED Laptop 16-inch",
    description: "Powerhouse performance meets stunning design. 16-inch 4K OLED display, latest gen processor, 32GB RAM, 1TB NVMe SSD, and all-day battery life.",
    price: 1899.99,
    comparePrice: 2299.99,
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800"],
    category: "Electronics",
    subcategory: "Laptops",
    brand: "TechVault",
    sku: "TV-LP-4K-001",
    stock: 75,
    rating: 4.9,
    reviewCount: 1823,
    tags: ["laptop", "4k", "oled", "ultraslim", "creator", "developer"],
    isFeatured: true,
  },
  {
    name: "Smart Fitness Watch Pro with AI Health Coach",
    description: "Your personal AI health companion. Tracks 100+ exercises, provides real-time form correction, sleep analysis, stress management, and predictive health insights.",
    price: 299.99,
    comparePrice: 399.99,
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800"],
    category: "Electronics",
    subcategory: "Wearables",
    brand: "FitGenius",
    sku: "FG-SW-PRO-001",
    stock: 200,
    rating: 4.7,
    reviewCount: 3891,
    tags: ["smartwatch", "fitness", "health", "AI", "wearable"],
    isFeatured: true,
  },
  {
    name: "4K Mirrorless Professional Camera Kit",
    description: "Capture stunning 4K video and 24MP photos. Includes full-frame mirrorless body, 24-70mm lens, and professional accessories for content creators.",
    price: 2499.99,
    comparePrice: 3199.99,
    images: ["https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800"],
    category: "Electronics",
    subcategory: "Cameras",
    brand: "PixelPro",
    sku: "PP-CAM-4K-001",
    stock: 40,
    rating: 4.9,
    reviewCount: 845,
    tags: ["camera", "4k", "mirrorless", "professional", "photography"],
    isFeatured: false,
  },
  {
    name: "Portable Bluetooth Speaker Waterproof",
    description: "360-degree sound with 30-hour battery life. Waterproof design, dual drivers, and deep bass for any environment.",
    price: 129.99,
    comparePrice: 179.99,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800"],
    category: "Electronics",
    subcategory: "Audio",
    brand: "SoundWave",
    sku: "SW-SP-BT-001",
    stock: 250,
    rating: 4.6,
    reviewCount: 1234,
    tags: ["speaker", "bluetooth", "waterproof", "portable"],
    isFeatured: false,
  },
  {
    name: "Gaming Monitor 4K 144Hz",
    description: "IPS panel with 99% DCI-P3 color gamut, 1ms response time, G-Sync and FreeSync support for ultimate gaming and design work.",
    price: 699.99,
    comparePrice: 899.99,
    images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?w=800"],
    category: "Electronics",
    subcategory: "Monitors",
    brand: "ViewMaster",
    sku: "VM-MON-4K-144",
    stock: 60,
    rating: 4.8,
    reviewCount: 2156,
    tags: ["monitor", "4k", "gaming", "144hz", "displayport"],
    isFeatured: true,
  },
  {
    name: "Mechanical Keyboard RGB Switches",
    description: "Premium mechanical keyboard with hot-swap RGB switches, aluminum frame, programmable macros, and wireless connectivity.",
    price: 189.99,
    comparePrice: 259.99,
    images: ["https://images.unsplash.com/photo-1587829191301-26e5b2800e2f?w=800"],
    category: "Electronics",
    subcategory: "Peripherals",
    brand: "KeyMaster",
    sku: "KM-KB-RGB-001",
    stock: 120,
    rating: 4.7,
    reviewCount: 1876,
    tags: ["keyboard", "mechanical", "rgb", "gaming", "wireless"],
    isFeatured: false,
  },
  {
    name: "Wireless Mouse Precision Pro",
    description: "Ultra-precise tracking with 16,000 DPI sensor, ergonomic design, 70-hour battery life, and ultra-responsive buttons.",
    price: 99.99,
    comparePrice: 129.99,
    images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?w=800"],
    category: "Electronics",
    subcategory: "Peripherals",
    brand: "PrecisionTech",
    sku: "PT-MOUSE-PRO-001",
    stock: 200,
    rating: 4.6,
    reviewCount: 1543,
    tags: ["mouse", "wireless", "gaming", "precision", "ergonomic"],
    isFeatured: false,
  },
  {
    name: "USB-C Hub 7-in-1 Docking Station",
    description: "Expand your laptop connectivity. HDMI 4K output, 100W power delivery, 3x USB 3.0, SD card reader, and Ethernet.",
    price: 79.99,
    comparePrice: 99.99,
    images: ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800"],
    category: "Electronics",
    subcategory: "Accessories",
    brand: "ConnectHub",
    sku: "CH-HUB-7IN1-001",
    stock: 300,
    rating: 4.5,
    reviewCount: 987,
    tags: ["hub", "usb-c", "docking", "accessories", "multiport"],
    isFeatured: false,
  },
  {
    name: "Phone Holder Car Magnetic Pro",
    description: "Secure your phone while driving. Strong magnetic grip, 360-degree rotation, and dashboard/windshield mounting options.",
    price: 29.99,
    comparePrice: 49.99,
    images: ["https://images.unsplash.com/photo-1605559424843-9e4c3ca3806d?w=800"],
    category: "Electronics",
    subcategory: "Accessories",
    brand: "DriveConnect",
    sku: "DC-PH-HOLDER-001",
    stock: 500,
    rating: 4.7,
    reviewCount: 2345,
    tags: ["phone", "holder", "car", "magnetic", "mount"],
    isFeatured: false,
  },
  {
    name: "Fast Charging Cable USB-C 5A",
    description: "Super durable braided cable, supports fast charging up to 5A, compatible with all USB-C devices, lifetime warranty.",
    price: 19.99,
    comparePrice: 29.99,
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800"],
    category: "Electronics",
    subcategory: "Cables",
    brand: "PowerLine",
    sku: "PL-CABLE-5A-001",
    stock: 1000,
    rating: 4.8,
    reviewCount: 4567,
    tags: ["cable", "usb-c", "charging", "fast", "durable"],
    isFeatured: false,
  },
  {
    name: "Tablet 12.9-inch OLED Pro",
    description: "Stunning 120Hz OLED display, M2 chip, 8GB RAM, 256GB storage, stylus included, perfect for designers and creators.",
    price: 1299.99,
    comparePrice: 1599.99,
    images: ["https://images.unsplash.com/photo-1574829185490-97e87c0c1f43?w=800"],
    category: "Electronics",
    subcategory: "Tablets",
    brand: "PixelTab",
    sku: "PT-TAB-OLED-001",
    stock: 80,
    rating: 4.9,
    reviewCount: 1234,
    tags: ["tablet", "oled", "stylus", "professional", "creative"],
    isFeatured: true,
  },
  {
    name: "Portable SSD 2TB Fast",
    description: "Read speeds up to 1050MB/s, rugged aluminum design, water and shock resistant, perfect for creators on the go.",
    price: 349.99,
    comparePrice: 449.99,
    images: ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800"],
    category: "Electronics",
    subcategory: "Storage",
    brand: "DataVault",
    sku: "DV-SSD-2TB-001",
    stock: 120,
    rating: 4.8,
    reviewCount: 2156,
    tags: ["ssd", "portable", "fast", "storage", "rugged"],
    isFeatured: false,
  },
  {
    name: "External Hard Drive 4TB USB 3.0",
    description: "4TB storage capacity, fast USB 3.0 transfer speeds, backup software included, 2-year warranty.",
    price: 119.99,
    comparePrice: 159.99,
    images: ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800"],
    category: "Electronics",
    subcategory: "Storage",
    brand: "StoragePro",
    sku: "SP-HDD-4TB-001",
    stock: 150,
    rating: 4.6,
    reviewCount: 1876,
    tags: ["harddrive", "external", "storage", "backup"],
    isFeatured: false,
  },
  {
    name: "USB-C Power Bank 30000mAh",
    description: "Massive capacity with 65W USB-C output. Charge multiple devices simultaneously, LED display, compact design.",
    price: 99.99,
    comparePrice: 139.99,
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800"],
    category: "Electronics",
    subcategory: "Power",
    brand: "PowerBank Pro",
    sku: "PBP-30K-USB-001",
    stock: 200,
    rating: 4.7,
    reviewCount: 2345,
    tags: ["powerbank", "usb-c", "charging", "portable", "fast"],
    isFeatured: false,
  },
  {
    name: "LED Ring Light Professional 18 inch",
    description: "Perfect for content creators. 3200-5600K color temperature, 10 brightness levels, includes tripod and phone holder.",
    price: 199.99,
    comparePrice: 279.99,
    images: ["https://images.unsplash.com/photo-1536337519179-79cdc3325127?w=800"],
    category: "Electronics",
    subcategory: "Lighting",
    brand: "BrightStudio",
    sku: "BS-RING-18-001",
    stock: 100,
    rating: 4.8,
    reviewCount: 1654,
    tags: ["ringlight", "lighting", "content", "creator", "tripod"],
    isFeatured: false,
  },
  {
    name: "Webcam 4K Ultra HD Pro",
    description: "Crystal clear 4K video at 30fps, built-in microphone, auto-focus technology, perfect for streaming and video calls.",
    price: 299.99,
    comparePrice: 399.99,
    images: ["https://images.unsplash.com/photo-1598986646514-ff979e34925c?w=800"],
    category: "Electronics",
    subcategory: "Cameras",
    brand: "StreamCam",
    sku: "SC-WEB-4K-001",
    stock: 90,
    rating: 4.7,
    reviewCount: 1234,
    tags: ["webcam", "4k", "streaming", "video", "microphone"],
    isFeatured: false,
  },
  {
    name: "WiFi 6 Router AX12000 Pro",
    description: "Ultra-fast WiFi 6 speeds, 12 Gbps throughput, covers 5000 sq ft, 8 antennas, perfect for smart homes and gaming.",
    price: 349.99,
    comparePrice: 449.99,
    images: ["https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800"],
    category: "Electronics",
    subcategory: "Networking",
    brand: "NetSpeed",
    sku: "NS-ROUTER-AX-001",
    stock: 70,
    rating: 4.6,
    reviewCount: 1987,
    tags: ["router", "wifi6", "networking", "gaming", "smarthome"],
    isFeatured: false,
  },
  {
    name: "Mesh WiFi System 3-Pack",
    description: "Whole home WiFi coverage, easy setup, self-healing mesh network, parental controls, compatible with all devices.",
    price: 249.99,
    comparePrice: 349.99,
    images: ["https://images.unsplash.com/photo-1607087916509-23ac4266fba0?w=800"],
    category: "Electronics",
    subcategory: "Networking",
    brand: "MeshNet",
    sku: "MN-MESH-3PACK-001",
    stock: 100,
    rating: 4.7,
    reviewCount: 2156,
    tags: ["mesh", "wifi", "networking", "coverage", "easy"],
    isFeatured: false,
  },

  // Fashion (20 items)
  {
    name: "Organic Cotton Sustainable Hoodie",
    description: "Eco-conscious comfort meets street style. Made from 100% organic cotton with recycled polyester blend. Carbon-neutral production.",
    price: 89.99,
    comparePrice: 129.99,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"],
    category: "Fashion",
    subcategory: "Hoodies",
    brand: "EcoThread",
    sku: "ET-HD-ORG-001",
    stock: 500,
    rating: 4.6,
    reviewCount: 1567,
    tags: ["hoodie", "organic", "sustainable", "fashion", "eco-friendly"],
    isFeatured: false,
  },
  {
    name: "Premium Denim Jeans Slim Fit",
    description: "Classic slim fit jeans made from premium Japanese denim. Comfortable, durable, with perfect fading pattern.",
    price: 129.99,
    comparePrice: 169.99,
    images: ["https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800"],
    category: "Fashion",
    subcategory: "Jeans",
    brand: "DenimPro",
    sku: "DP-JEANS-SF-001",
    stock: 300,
    rating: 4.7,
    reviewCount: 2134,
    tags: ["jeans", "denim", "slim", "fashion", "casual"],
    isFeatured: false,
  },
  {
    name: "Minimalist Leather Backpack - Italian Craftsmanship",
    description: "Full-grain Italian leather with water-resistant coating. Padded 16-inch laptop compartment, RFID-blocking pocket.",
    price: 259.99,
    comparePrice: 349.99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"],
    category: "Fashion",
    subcategory: "Bags",
    brand: "Artigiano",
    sku: "AR-BP-LTR-001",
    stock: 70,
    rating: 4.7,
    reviewCount: 654,
    tags: ["backpack", "leather", "italian", "minimalist", "laptop"],
    isFeatured: true,
  },
  {
    name: "Casual Athletic T-Shirt Tech Fabric",
    description: "Breathable moisture-wicking fabric, anti-odor technology, perfect for gym or casual wear.",
    price: 49.99,
    comparePrice: 79.99,
    images: ["https://images.unsplash.com/photo-1527689377108-f78f29994c53?w=800"],
    category: "Fashion",
    subcategory: "T-Shirts",
    brand: "ActiveWear",
    sku: "AW-TSHIRT-001",
    stock: 400,
    rating: 4.5,
    reviewCount: 1876,
    tags: ["tshirt", "athletic", "breathable", "casual", "tech"],
    isFeatured: false,
  },
  {
    name: "Winter Parka Waterproof Insulated",
    description: "Warm and waterproof winter parka with thermal insulation, multiple pockets, and adjustable hood.",
    price: 349.99,
    comparePrice: 449.99,
    images: ["https://images.unsplash.com/photo-1539533057592-4ee49ce8b47d?w=800"],
    category: "Fashion",
    subcategory: "Jackets",
    brand: "WinterGear",
    sku: "WG-PARKA-001",
    stock: 150,
    rating: 4.8,
    reviewCount: 1234,
    tags: ["parka", "winter", "waterproof", "warm", "insulated"],
    isFeatured: false,
  },
  {
    name: "Yoga Pants High Waist Comfort",
    description: "Flexible high-waist yoga pants with hidden pockets, squat-proof, and four-way stretch fabric.",
    price: 79.99,
    comparePrice: 119.99,
    images: ["https://images.unsplash.com/photo-1506629082847-11d3e392e467?w=800"],
    category: "Fashion",
    subcategory: "Leggings",
    brand: "YogaFlow",
    sku: "YF-PANTS-HW-001",
    stock: 250,
    rating: 4.6,
    reviewCount: 1543,
    tags: ["yoga", "pants", "leggings", "comfortable", "flexible"],
    isFeatured: false,
  },
  {
    name: "Casual Sneakers Comfortable Walking Shoes",
    description: "Ergonomic design with memory foam insole, breathable mesh, lightweight and perfect for all-day comfort.",
    price: 119.99,
    comparePrice: 159.99,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
    category: "Fashion",
    subcategory: "Shoes",
    brand: "ComfortStride",
    sku: "CS-SHOES-001",
    stock: 300,
    rating: 4.7,
    reviewCount: 2456,
    tags: ["shoes", "sneakers", "casual", "comfortable", "walking"],
    isFeatured: false,
  },
  {
    name: "Formal Dress Shirt Premium Cotton",
    description: "Classic formal shirt in premium cotton with perfect fit and easy care. Perfect for office or special occasions.",
    price: 89.99,
    comparePrice: 129.99,
    images: ["https://images.unsplash.com/photo-1596399579883-e826ae0ed1d0?w=800"],
    category: "Fashion",
    subcategory: "Shirts",
    brand: "FormalWear",
    sku: "FW-SHIRT-001",
    stock: 200,
    rating: 4.6,
    reviewCount: 1123,
    tags: ["shirt", "formal", "cotton", "dress", "office"],
    isFeatured: false,
  },
  {
    name: "Casual Blazer Comfortable Fit",
    description: "Perfect blazer for business casual. Wrinkle-resistant fabric, single breasted, comfortable all-day wear.",
    price: 199.99,
    comparePrice: 279.99,
    images: ["https://images.unsplash.com/photo-1518819194849-c5bd77d8c6ad?w=800"],
    category: "Fashion",
    subcategory: "Outerwear",
    brand: "StylePro",
    sku: "SP-BLAZER-001",
    stock: 100,
    rating: 4.5,
    reviewCount: 876,
    tags: ["blazer", "casual", "business", "comfortable", "formal"],
    isFeatured: false,
  },
  {
    name: "Summer Dress Flowy Light Fabric",
    description: "Light and flowy summer dress perfect for warm weather. Breathable fabric, comfortable fit, stylish design.",
    price: 69.99,
    comparePrice: 99.99,
    images: ["https://images.unsplash.com/photo-1595586233223-62109e82a660?w=800"],
    category: "Fashion",
    subcategory: "Dresses",
    brand: "SummerVibes",
    sku: "SV-DRESS-001",
    stock: 200,
    rating: 4.6,
    reviewCount: 1234,
    tags: ["dress", "summer", "flowy", "light", "comfortable"],
    isFeatured: false,
  },
  {
    name: "Wool Sweater Cozy Warm",
    description: "Soft wool sweater perfect for cold weather. Machine washable, versatile style, warm and comfortable.",
    price: 129.99,
    comparePrice: 179.99,
    images: ["https://images.unsplash.com/photo-1574367692952-1c92e04bf126?w=800"],
    category: "Fashion",
    subcategory: "Sweaters",
    brand: "WarmKnits",
    sku: "WK-SWEATER-001",
    stock: 150,
    rating: 4.7,
    reviewCount: 1456,
    tags: ["sweater", "wool", "cozy", "warm", "comfortable"],
    isFeatured: false,
  },
  {
    name: "Leather Belt Premium Quality",
    description: "Genuine leather belt with quality buckle. Durable, versatile, perfect for any outfit.",
    price: 79.99,
    comparePrice: 119.99,
    images: ["https://images.unsplash.com/photo-1624526267942-ab67cb38121d?w=800"],
    category: "Fashion",
    subcategory: "Accessories",
    brand: "LeatherPro",
    sku: "LP-BELT-001",
    stock: 300,
    rating: 4.6,
    reviewCount: 987,
    tags: ["belt", "leather", "premium", "quality", "accessories"],
    isFeatured: false,
  },
  {
    name: "Silk Scarf Elegant Colorful",
    description: "Beautiful silk scarf with vibrant colors. Versatile accessory perfect for any season.",
    price: 59.99,
    comparePrice: 89.99,
    images: ["https://images.unsplash.com/photo-1598626046486-3b78ae1820fa?w=800"],
    category: "Fashion",
    subcategory: "Accessories",
    brand: "ElegantSilk",
    sku: "ES-SCARF-001",
    stock: 250,
    rating: 4.5,
    reviewCount: 654,
    tags: ["scarf", "silk", "elegant", "colorful", "accessories"],
    isFeatured: false,
  },
  {
    name: "Baseball Cap Classic Style",
    description: "Classic baseball cap with adjustable strap. Perfect for casual outfits or outdoor activities.",
    price: 39.99,
    comparePrice: 59.99,
    images: ["https://images.unsplash.com/photo-1613165571878-9e8a0f82dcc8?w=800"],
    category: "Fashion",
    subcategory: "Hats",
    brand: "CapStyle",
    sku: "CS-CAP-001",
    stock: 400,
    rating: 4.4,
    reviewCount: 876,
    tags: ["cap", "baseball", "classic", "casual", "outdoor"],
    isFeatured: false,
  },
  {
    name: "Sunglasses UV Protection Polarized",
    description: "Stylish sunglasses with UV protection and polarized lenses. Comfortable for all-day wear.",
    price: 149.99,
    comparePrice: 199.99,
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800"],
    category: "Fashion",
    subcategory: "Eyewear",
    brand: "SunStyle",
    sku: "SS-GLASSES-001",
    stock: 200,
    rating: 4.6,
    reviewCount: 1234,
    tags: ["sunglasses", "uv", "polarized", "protection", "eyewear"],
    isFeatured: false,
  },
  {
    name: "Wool Socks Soft Comfortable Pack",
    description: "Pack of 5 soft wool socks. Warm, comfortable, perfect for cold weather.",
    price: 29.99,
    comparePrice: 49.99,
    images: ["https://images.unsplash.com/photo-1611033225433-252211f82b47?w=800"],
    category: "Fashion",
    subcategory: "Socks",
    brand: "ComfortSocks",
    sku: "CS-SOCKS-5PACK",
    stock: 500,
    rating: 4.5,
    reviewCount: 654,
    tags: ["socks", "wool", "comfortable", "warm", "pack"],
    isFeatured: false,
  },
  {
    name: "Handbag Elegant Structured",
    description: "Elegant structured handbag perfect for work or casual outings. Quality leather, multiple compartments.",
    price: 199.99,
    comparePrice: 299.99,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800"],
    category: "Fashion",
    subcategory: "Bags",
    brand: "ElegantBags",
    sku: "EB-HANDBAG-001",
    stock: 80,
    rating: 4.7,
    reviewCount: 789,
    tags: ["handbag", "elegant", "structured", "leather", "quality"],
    isFeatured: false,
  },

  // Home & Kitchen (20 items)
  {
    name: "Professional Chef's Knife Set - Damascus Steel",
    description: "Hand-forged Damascus steel knife set with 67 layers. Includes 8-inch chef's knife, 6-inch utility, 3.5-inch paring knife, and magnetic walnut block. Lifetime warranty.",
    price: 249.99,
    comparePrice: 349.99,
    images: ["https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800"],
    category: "Home & Kitchen",
    subcategory: "Knives",
    brand: "BladeForge",
    sku: "BF-KS-DAM-001",
    stock: 80,
    rating: 4.9,
    reviewCount: 945,
    tags: ["knife", "chef", "damascus", "kitchen", "professional", "cooking"],
    isFeatured: true,
  },
  {
    name: "AI-Powered Robot Vacuum & Mop Combo",
    description: "Advanced LiDAR navigation with AI object recognition. Maps your home in 3D, avoids obstacles, self-empties, and provides scheduled deep cleaning.",
    price: 599.99,
    comparePrice: 799.99,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800"],
    category: "Home & Kitchen",
    subcategory: "Smart Home",
    brand: "CleanBot",
    sku: "CB-RV-AI-001",
    stock: 120,
    rating: 4.7,
    reviewCount: 2103,
    tags: ["robot vacuum", "AI", "smart home", "cleaning", "automated"],
    isFeatured: true,
  },
  {
    name: "Smart Indoor Garden with AI Growth Optimization",
    description: "Grow fresh herbs and vegetables year-round. AI monitors light, water, and nutrients automatically. Supports 12 pods simultaneously.",
    price: 149.99,
    comparePrice: 199.99,
    images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800"],
    category: "Home & Kitchen",
    subcategory: "Garden",
    brand: "GrowGenius",
    sku: "GG-IG-AI-001",
    stock: 140,
    rating: 4.4,
    reviewCount: 892,
    tags: ["garden", "indoor", "smart", "AI", "herbs", "sustainable"],
    isFeatured: false,
  },
  {
    name: "Premium Espresso Machine with Grinder",
    description: "Café-quality espresso anywhere. Built-in ceramic burr grinder, 15-bar pressure pump, USB-C rechargeable battery. Makes both hot and cold brew.",
    price: 179.99,
    comparePrice: 249.99,
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800"],
    category: "Home & Kitchen",
    subcategory: "Coffee",
    brand: "BrewMaster",
    sku: "BM-PE-GR-001",
    stock: 180,
    rating: 4.6,
    reviewCount: 1876,
    tags: ["espresso", "coffee", "portable", "grinder", "travel"],
    isFeatured: true,
  },
  {
    name: "Non-Stick Cookware Set 10 Pieces",
    description: "Premium non-stick cookware set including pots, pans, and utensils. Oven safe up to 500°F, heat-resistant handles.",
    price: 199.99,
    comparePrice: 299.99,
    images: ["https://images.unsplash.com/photo-1522663596957-46df83b7a45d?w=800"],
    category: "Home & Kitchen",
    subcategory: "Cookware",
    brand: "ChefKit",
    sku: "CK-COOKWARE-10",
    stock: 100,
    rating: 4.6,
    reviewCount: 1567,
    tags: ["cookware", "nonstick", "kitchen", "cooking", "set"],
    isFeatured: false,
  },
  {
    name: "Smart Oven Digital Countertop",
    description: "Multifunctional smart oven with digital controls. Convection, air fry, toast, and more. Voice control compatible.",
    price: 399.99,
    comparePrice: 499.99,
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800"],
    category: "Home & Kitchen",
    subcategory: "Appliances",
    brand: "SmartChef",
    sku: "SC-OVEN-SMART",
    stock: 60,
    rating: 4.7,
    reviewCount: 1234,
    tags: ["oven", "smart", "digital", "convection", "airfry"],
    isFeatured: false,
  },
  {
    name: "Blender Pro High-Speed Power",
    description: "Powerful 2.2HP motor, variable speed control, makes smoothies, nut butter, and soups in seconds.",
    price: 299.99,
    comparePrice: 399.99,
    images: ["https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=800"],
    category: "Home & Kitchen",
    subcategory: "Appliances",
    brand: "PowerBlend",
    sku: "PB-BLENDER-PRO",
    stock: 90,
    rating: 4.8,
    reviewCount: 2156,
    tags: ["blender", "high-speed", "powerful", "smoothie", "kitchen"],
    isFeatured: false,
  },
  {
    name: "Air Fryer 5.5L Digital Temperature Control",
    description: "Healthy frying with air circulation technology. Large capacity, digital temperature control, dishwasher safe.",
    price: 119.99,
    comparePrice: 179.99,
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800"],
    category: "Home & Kitchen",
    subcategory: "Appliances",
    brand: "AirFry",
    sku: "AF-AIRFRYER-5.5L",
    stock: 150,
    rating: 4.7,
    reviewCount: 2341,
    tags: ["airfryer", "healthy", "digital", "fryer", "kitchen"],
    isFeatured: false,
  },
  {
    name: "Stainless Steel Refrigerator Filter",
    description: "Replacement filter for refrigerators. Removes chlorine, odor, and bad taste. Easy installation.",
    price: 39.99,
    comparePrice: 59.99,
    images: ["https://images.unsplash.com/photo-1584568694244-14fbbc83bd30?w=800"],
    category: "Home & Kitchen",
    subcategory: "Filters",
    brand: "PureWater",
    sku: "PW-FILTER-REF",
    stock: 300,
    rating: 4.5,
    reviewCount: 876,
    tags: ["filter", "refrigerator", "water", "replacement"],
    isFeatured: false,
  },
  {
    name: "Glass Food Storage Containers Set",
    description: "Set of 10 glass containers with airtight lids. Microwave, dishwasher, and oven safe.",
    price: 59.99,
    comparePrice: 89.99,
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800"],
    category: "Home & Kitchen",
    subcategory: "Storage",
    brand: "FreshKeep",
    sku: "FK-CONTAINERS-10",
    stock: 200,
    rating: 4.6,
    reviewCount: 1543,
    tags: ["containers", "glass", "storage", "fresh", "microwave"],
    isFeatured: false,
  },
  {
    name: "Bamboo Cutting Board Set 3 Sizes",
    description: "Set of 3 bamboo cutting boards in different sizes. Eco-friendly, durable, and naturally antimicrobial.",
    price: 49.99,
    comparePrice: 79.99,
    images: ["https://images.unsplash.com/photo-1577003833535-08175d352632?w=800"],
    category: "Home & Kitchen",
    subcategory: "Cutting Boards",
    brand: "EcoChop",
    sku: "EC-CUTTINGBOARD-3",
    stock: 250,
    rating: 4.5,
    reviewCount: 1234,
    tags: ["cutting board", "bamboo", "eco-friendly", "durable", "kitchen"],
    isFeatured: false,
  },
  {
    name: "Stainless Steel Mixing Bowl Set 5 Piece",
    description: "Set of 5 mixing bowls in various sizes. Stainless steel construction, non-slip base.",
    price: 49.99,
    comparePrice: 79.99,
    images: ["https://images.unsplash.com/photo-1595521624593-2d4c2c0a2a87?w=800"],
    category: "Home & Kitchen",
    subcategory: "Mixing Bowls",
    brand: "KitchenPro",
    sku: "KP-MIXBOWL-5",
    stock: 200,
    rating: 4.6,
    reviewCount: 987,
    tags: ["mixing bowl", "stainless steel", "kitchen", "set", "nonslip"],
    isFeatured: false,
  },
  {
    name: "Electric Kettle Fast Boil 1.7L",
    description: "Quick boil electric kettle with auto-shutoff and dry-boil protection. Stainless steel construction.",
    price: 49.99,
    comparePrice: 79.99,
    images: ["https://images.unsplash.com/photo-1578413915015-84cc0db02c33?w=800"],
    category: "Home & Kitchen",
    subcategory: "Kettle",
    brand: "QuickBoil",
    sku: "QB-KETTLE-1.7L",
    stock: 300,
    rating: 4.7,
    reviewCount: 1654,
    tags: ["kettle", "electric", "fast", "boil", "stainless"],
    isFeatured: false,
  },
  {
    name: "Coffee Maker Drip 12 Cup Capacity",
    description: "Large capacity coffee maker with programmable timer. Keep warm function, easy to clean.",
    price: 79.99,
    comparePrice: 119.99,
    images: ["https://images.unsplash.com/photo-1508615039623-a25605d2938d?w=800"],
    category: "Home & Kitchen",
    subcategory: "Coffee",
    brand: "BrewPerfect",
    sku: "BP-COFFEE-12CUP",
    stock: 120,
    rating: 4.6,
    reviewCount: 1234,
    tags: ["coffee", "maker", "drip", "programmable", "timer"],
    isFeatured: false,
  },
  {
    name: "Dishwasher Safe Utensil Set",
    description: "Set of 20 kitchen utensils including spoons, forks, knives. Dishwasher safe, durable stainless steel.",
    price: 39.99,
    comparePrice: 59.99,
    images: ["https://images.unsplash.com/photo-1610107588557-37e3b7a0dcc4?w=800"],
    category: "Home & Kitchen",
    subcategory: "Utensils",
    brand: "SilverChef",
    sku: "SC-UTENSIL-20",
    stock: 300,
    rating: 4.5,
    reviewCount: 876,
    tags: ["utensil", "dishwasher", "stainless", "kitchen", "set"],
    isFeatured: false,
  },
  {
    name: "Shower Caddy Hanging Organizer",
    description: "Hanging shower caddy with multiple compartments. Rust-proof stainless steel.",
    price: 29.99,
    comparePrice: 49.99,
    images: ["https://images.unsplash.com/photo-1584622675529-1b48456db0ae?w=800"],
    category: "Home & Kitchen",
    subcategory: "Bathroom",
    brand: "OrganiClean",
    sku: "OC-CADDY-SHOWER",
    stock: 400,
    rating: 4.4,
    reviewCount: 654,
    tags: ["caddy", "shower", "organizer", "hanging", "rustproof"],
    isFeatured: false,
  },
  {
    name: "Microfiber Kitchen Towel Pack",
    description: "Pack of 8 microfiber kitchen towels. Highly absorbent, machine washable.",
    price: 24.99,
    comparePrice: 39.99,
    images: ["https://images.unsplash.com/photo-1584568694244-14fbbc83bd30?w=800"],
    category: "Home & Kitchen",
    subcategory: "Towels",
    brand: "AbsorbMax",
    sku: "AM-TOWEL-8PACK",
    stock: 500,
    rating: 4.5,
    reviewCount: 1234,
    tags: ["towel", "microfiber", "kitchen", "absorbent", "pack"],
    isFeatured: false,
  },

  // Furniture (20 items)
  {
    name: "Ergonomic Standing Desk with AI Posture Reminder",
    description: "Height-adjustable standing desk with built-in AI posture monitoring. Wireless charging pad, cable management system.",
    price: 699.99,
    comparePrice: 899.99,
    images: ["https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800"],
    category: "Furniture",
    subcategory: "Office",
    brand: "ErgoFlow",
    sku: "EF-SD-AI-001",
    stock: 60,
    rating: 4.8,
    reviewCount: 756,
    tags: ["standing desk", "ergonomic", "AI", "office", "health", "posture"],
    isFeatured: false,
  },
  {
    name: "Premium Office Chair Mesh Back",
    description: "High-back office chair with mesh backing, lumbar support, and adjustable armrests. Perfect for long working hours.",
    price: 399.99,
    comparePrice: 499.99,
    images: ["https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800"],
    category: "Furniture",
    subcategory: "Office",
    brand: "OfficeMax",
    sku: "OM-CHAIR-MESH",
    stock: 80,
    rating: 4.7,
    reviewCount: 1234,
    tags: ["office chair", "mesh", "lumbar", "ergonomic", "support"],
    isFeatured: false,
  },
  {
    name: "Comfortable Sofa 3-Seater Modern",
    description: "Modern 3-seater sofa with comfortable cushions and clean lines. Perfect for living rooms.",
    price: 799.99,
    comparePrice: 999.99,
    images: ["https://images.unsplash.com/photo-1540932239986-310128078ceb?w=800"],
    category: "Furniture",
    subcategory: "Living Room",
    brand: "ModernLiving",
    sku: "ML-SOFA-3SEAT",
    stock: 30,
    rating: 4.8,
    reviewCount: 654,
    tags: ["sofa", "modern", "comfortable", "3-seater", "livingroom"],
    isFeatured: true,
  },
  {
    name: "Coffee Table Wood & Metal Modern",
    description: "Stylish coffee table with wood top and metal frame. Perfect for modern living rooms.",
    price: 199.99,
    comparePrice: 299.99,
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800"],
    category: "Furniture",
    subcategory: "Living Room",
    brand: "ModernStyle",
    sku: "MS-TABLE-COFFEE",
    stock: 100,
    rating: 4.6,
    reviewCount: 876,
    tags: ["table", "coffee", "modern", "wood", "metal"],
    isFeatured: false,
  },
  {
    name: "Queen Size Bed Frame Wood Platform",
    description: "Sturdy queen size bed frame with wood platform. No box spring needed, minimalist design.",
    price: 399.99,
    comparePrice: 599.99,
    images: ["https://images.unsplash.com/photo-1605691556157-c5a88a93d26f?w=800"],
    category: "Furniture",
    subcategory: "Bedroom",
    brand: "SleepBetter",
    sku: "SB-BED-QUEEN",
    stock: 50,
    rating: 4.7,
    reviewCount: 1234,
    tags: ["bed", "queen", "wood", "platform", "bedroom"],
    isFeatured: false,
  },
  {
    name: "Nightstand with Drawer Storage",
    description: "Modern nightstand with drawer and open shelf storage. Perfect for bedside essentials.",
    price: 129.99,
    comparePrice: 179.99,
    images: ["https://images.unsplash.com/photo-1503619793487-9c2f8e92edd9?w=800"],
    category: "Furniture",
    subcategory: "Bedroom",
    brand: "BedComfort",
    sku: "BC-NIGHTSTAND-1",
    stock: 120,
    rating: 4.5,
    reviewCount: 765,
    tags: ["nightstand", "storage", "drawer", "bedroom", "modern"],
    isFeatured: false,
  },
  {
    name: "Wardrobe Cabinet 4 Door Wood",
    description: "Large 4-door wooden wardrobe with multiple shelves and hanging space. Perfect for organizing clothes.",
    price: 599.99,
    comparePrice: 799.99,
    images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800"],
    category: "Furniture",
    subcategory: "Bedroom",
    brand: "OrganizedLiving",
    sku: "OL-WARDROBE-4DR",
    stock: 40,
    rating: 4.6,
    reviewCount: 654,
    tags: ["wardrobe", "cabinet", "wood", "storage", "clothes"],
    isFeatured: false,
  },
  {
    name: "Dining Table 6-Seater Wood",
    description: "Beautiful 6-seater dining table with solid wood construction. Perfect for family dinners.",
    price: 699.99,
    comparePrice: 899.99,
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    category: "Furniture",
    subcategory: "Dining",
    brand: "DiningDream",
    sku: "DD-TABLE-6SEAT",
    stock: 35,
    rating: 4.7,
    reviewCount: 987,
    tags: ["table", "dining", "6-seater", "wood", "family"],
    isFeatured: false,
  },
  {
    name: "Dining Chair Set 4 Pieces",
    description: "Set of 4 comfortable dining chairs with wooden frame and cushioned seats.",
    price: 299.99,
    comparePrice: 399.99,
    images: ["https://images.unsplash.com/photo-1557109351-641a0ac8b3e7?w=800"],
    category: "Furniture",
    subcategory: "Dining",
    brand: "ComfortSeating",
    sku: "CS-CHAIR-4PACK",
    stock: 60,
    rating: 4.6,
    reviewCount: 765,
    tags: ["chair", "dining", "comfortable", "cushioned", "set"],
    isFeatured: false,
  },
  {
    name: "Bookshelf 5-Tier Wood Storage",
    description: "5-tier wooden bookshelf with sturdy construction. Perfect for displaying books and decorative items.",
    price: 179.99,
    comparePrice: 249.99,
    images: ["https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800"],
    category: "Furniture",
    subcategory: "Storage",
    brand: "StorageMax",
    sku: "SM-SHELF-5TIER",
    stock: 100,
    rating: 4.5,
    reviewCount: 654,
    tags: ["bookshelf", "storage", "wood", "5-tier", "display"],
    isFeatured: false,
  },
  {
    name: "TV Stand Modern Entertainment",
    description: "Modern TV stand with shelves for media equipment. Sleek design, supports up to 65-inch TV.",
    price: 249.99,
    comparePrice: 349.99,
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800"],
    category: "Furniture",
    subcategory: "Living Room",
    brand: "EntertainPro",
    sku: "EP-TVSTAND-MOD",
    stock: 75,
    rating: 4.6,
    reviewCount: 876,
    tags: ["tvstand", "entertainment", "modern", "storage", "media"],
    isFeatured: false,
  },
  {
    name: "Accent Chair Comfortable Lounge",
    description: "Comfortable accent chair perfect for reading or relaxing. Upholstered in soft fabric.",
    price: 299.99,
    comparePrice: 399.99,
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800"],
    category: "Furniture",
    subcategory: "Living Room",
    brand: "RelaxZone",
    sku: "RZ-CHAIR-ACCENT",
    stock: 70,
    rating: 4.7,
    reviewCount: 987,
    tags: ["chair", "accent", "comfortable", "lounge", "relax"],
    isFeatured: false,
  },
  {
    name: "Desk Lamp LED Reading Light",
    description: "Adjustable LED desk lamp with touch control. Perfect for reading or working.",
    price: 79.99,
    comparePrice: 119.99,
    images: ["https://images.unsplash.com/photo-1565610020461-ba2cf46e4b0c?w=800"],
    category: "Furniture",
    subcategory: "Lighting",
    brand: "BrightSpace",
    sku: "BS-LAMP-DESK",
    stock: 150,
    rating: 4.6,
    reviewCount: 765,
    tags: ["lamp", "desk", "led", "reading", "lighting"],
    isFeatured: false,
  },
  {
    name: "Floor Lamp Arc Metal Modern",
    description: "Modern arc floor lamp with metal construction. Perfect for adding ambient lighting to any room.",
    price: 149.99,
    comparePrice: 199.99,
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800"],
    category: "Furniture",
    subcategory: "Lighting",
    brand: "ModernLight",
    sku: "ML-LAMP-ARC",
    stock: 100,
    rating: 4.5,
    reviewCount: 654,
    tags: ["lamp", "floor", "arc", "modern", "metal"],
    isFeatured: false,
  },
  {
    name: "Wall Mounted Shelf Floating",
    description: "Modern floating wall shelf. Perfect for displaying books, photos, and decorative items.",
    price: 79.99,
    comparePrice: 119.99,
    images: ["https://images.unsplash.com/photo-1595521624593-2d4c2c0a2a87?w=800"],
    category: "Furniture",
    subcategory: "Storage",
    brand: "WallDecor",
    sku: "WD-SHELF-FLOAT",
    stock: 200,
    rating: 4.4,
    reviewCount: 654,
    tags: ["shelf", "floating", "wall", "storage", "modern"],
    isFeatured: false,
  },
  {
    name: "Room Divider Folding Screen",
    description: "Decorative folding room divider. Perfect for creating separate spaces and adding style.",
    price: 119.99,
    comparePrice: 169.99,
    images: ["https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800"],
    category: "Furniture",
    subcategory: "Decor",
    brand: "SpaceStyle",
    sku: "SS-DIVIDER-FOLD",
    stock: 80,
    rating: 4.5,
    reviewCount: 765,
    tags: ["divider", "folding", "screen", "space", "decor"],
    isFeatured: false,
  },
  {
    name: "Area Rug Modern Pattern 5x7",
    description: "Beautiful area rug with modern pattern. Durable, easy to clean, perfect for any room.",
    price: 199.99,
    comparePrice: 299.99,
    images: ["https://images.unsplash.com/photo-1598928506696-6e48ee1baabc?w=800"],
    category: "Furniture",
    subcategory: "Decor",
    brand: "HomeStyle",
    sku: "HS-RUG-5X7",
    stock: 60,
    rating: 4.6,
    reviewCount: 876,
    tags: ["rug", "area", "modern", "pattern", "floor"],
    isFeatured: false,
  },
  {
    name: "Wall Art Canvas Painting",
    description: "Beautiful canvas wall art in modern style. Perfect for decorating any room.",
    price: 99.99,
    comparePrice: 149.99,
    images: ["https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=800"],
    category: "Furniture",
    subcategory: "Decor",
    brand: "ArtGallery",
    sku: "AG-ART-CANVAS",
    stock: 150,
    rating: 4.5,
    reviewCount: 654,
    tags: ["art", "canvas", "painting", "wall", "decor"],
    isFeatured: false,
  },
];

const categories = [
  { name: "Electronics", slug: "electronics", description: "Latest gadgets and tech" },
  { name: "Fashion", slug: "fashion", description: "Clothing, shoes & accessories" },
  { name: "Home & Kitchen", slug: "home-kitchen", description: "Everything for your home" },
  { name: "Furniture", slug: "furniture", description: "Modern furniture & decor" },
];

async function main() {
  console.log("🌱 Starting expanded seed...");

  // Create categories
  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: {},
      create: category,
    });
  }
  console.log("✅ Categories seeded");

  // Create products with random embeddings
  for (const product of products) {
    const embedding = Array.from({ length: 384 }, () => Math.random() * 2 - 1);
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: {},
      create: {
        ...product,
        embedding,
      },
    });
  }
  console.log(`✅ ${products.length} products seeded`);

  // Create admin user
  const { default: bcrypt } = await import("bcryptjs");
  const hashedPassword = await bcrypt.hash("admin123", 12);
  
  await prisma.user.upsert({
    where: { email: "admin@nexusai.shop" },
    update: {},
    create: {
      name: "Admin User",
      email: "admin@nexusai.shop",
      hashedPassword,
      role: "ADMIN",
    },
  });
  console.log("✅ Admin user seeded");

  console.log("🎉 Expanded seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
